### ISSUE TITLE
Sofawiki 3.5.3 throws  syntax error on PHP 5.4

### ISSUE THREAD

**Issue by prbt2016** [bellenuit/sofawiki#20]
Hello,

I was in the process of manual installation of Sofawiki on CentOS Linux release 7.7.1908 (Core) with PHP 5.4, Apache 2.2.

However I encountered the following error while starting the installation i.e : 

```
Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /{{PATH}}/{{TO}}/{{SOFAWIKI}}/inc/dba.php on line 413 
```

I  get the same error on PHP 5.4 - 5.6 . However installation works fine on PHP 7.0.

Could you please try to replicate the error at your end on PHP < 7.0? 

Also it is mentioned on official site in the link below that SofaWiki works on PHP 5.4 : 

https://www.sofawiki.com/en/software-requirements

Are the requirements changed?. What is the minimum PHP version required to run SofaWiki.

**Comment by bellenuit** [comment]
swDBA->list() is a stub function and list seems to be a reserved word. I will rename it in 3.5.4 because it is actually not yet used.

**Comment by prbt2016** [comment]
Hello,

Thanks. I checked with Sofawiki 3.5.4 and it's working fine without any issues.
You can close this issue.

Regards.
