### ISSUE TITLE
Getting issue in install of SofaWiki 3.7.1

### ISSUE THREAD

**Issue by GaneshKandu** [bellenuit/sofawiki#21]
1. I am Trying to install SofaWiki 3.7.0 but while install i noticed ```install``` and ```install and delete install.php``` button do not working.
no get and post request in network tab of browser.
2. I have disabled error display in php.ini still i am getting this error while install
```Notice: Undefined variable: langoptions in inc/special/install.php on line 95 Notice: Undefined variable: skinoptions in inc/special/install.php on line 106 ```

**Comment by GaneshKandu** [comment]
same issue persist in SofaWiki 3.7.1 also.

**Comment by bellenuit** [comment]
Fixed 3.7.2
