### ISSUE TITLE
Sofawiki 3.7.6 issues

### ISSUE THREAD

**Issue by prbt2016** [bellenuit/sofawiki#23]
Hello,

I was in the process of manual installation of Sofawiki 3.7.6 on CentOS Linux release 7.9.2009 (Core) with PHP 5.4.45, Apache 2.2.34 using the Source code package i.e : 

https://www.sofawiki.com/site/files/snapshot.zip

However I encountered issues i.e : 

1) On visiting the admin panel when I visit :

New -> Upload -> Click on Upload button and uploaded image is not shown, instead the URL is redirected index page to 

http://{{URL}}/index.php

2) When I visit Special -> Tickets -> New Ticket -> Enter title , text , then browse the image and click on 'Open' Ticket the following error is thrown i.e : 

`Fatal error: Call to undefined function substr() in /{{PATH}}/{{TO}}/{{SOFAWIKI}}/inc/special/tickets.php on line 77`

Also I checked line 77 in tickets.php the code substr() function is defined. Yet it throws the same issue.

Checked on another server as well , there also getting the same error thrown.

Could you please replicate the issue at your end and fix this?.

**Comment by prbt2016** [comment]
Any updates regarding the same?.

**Comment by bellenuit** [comment]
included in 3.7.7

**Comment by prbt2016** [comment]
Hello @bellenuit ,

I checked 3.7.7.

Images are uploaded properly on creating New Ticket . 

However  there are few issues i.e : 

1) On visiting the admin panel when I visit :

New -> Upload -> Click on Upload button and uploaded image is not shown, instead the URL is redirected index page to

http://{{URL}}/index.php

Same happens on visiting Special->Upload and try to upload an image, page is redirected to index and no image is shown . also it's shown in List -> Images

2) On visiting Special -> Upload Big , image gets uploaded but on visiting the image URL which is shown in same dialog 

http://example.com/manual/sofawiki/index.php?name=Image:logo.gif

Following description is shown instead of the image i.e : 


Image:logo.gif
[[imagechecksum::30cdadb61f4190780f7349b355dd8b95]]

[[filesize::22350]]
[[uploadtime::0]]
[[comment::testet]]

3) On visiting Special -> Upload Multiple following error is shown i.e 

Upload multiple
All files in the Upload directory will be moved to the file directory and image pages will be created

No file found .

Could you please check and fix these as well ?

**Comment by prbt2016** [comment]
Hello @bellenuit ,

Any updates regarding the same ?.

**Comment by bellenuit** [comment]
I will look on it this week

Envoyé de mon iPhone

**Comment by bellenuit** [comment]
On 1: This was broken. Will be fixed in 3.7.8
On 2: Image Page viewer did not show images with some extensions. Will be fixed in 3.7.8
On 3: This is no error: Upload multiple does batch import images you have manually placed in the site/upload/ folder. If that folder is empty, this message is shown. See https://www.sofawiki.com/en/inc-special-uploadmultiple-php

**Comment by prbt2016** [comment]
Hello @bellenuit ,

Thanks a lot for looking into the issue . Shall check 3.7.8.

Regards.

**Comment by prbt2016** [comment]
Hello @bellenuit ,

I was in the process of manual installation of Sofawiki 3.7.8 on Centos 7 with PHP 5.4, Apache 2.2.34 .

However the following warning is thrown on entering details and clicking install i.e 

 Warning: Cannot modify header information - headers already sent by (output started at /{{PATH}}/{{TO}}/{{SOFAWIKI}}/index.php:318) in /{{PATH}}/{{TO}}/{{SOFAWIKI}}/inc/special/install.php on line 79

For your kind information I have errors i.e (display_errors=Off) turned off in my php.ini file.

Could you please check this at your end and fix this. As I have checked on another server as well. 

There also I get the same issue.

**Comment by bellenuit** [comment]
I tried to install on Cpanel and PHO 5.4, Apache 2.5.53 and I cannot reproduce the error though I can theroretically imagine what could happen.
I used the install.php script.
Did you use that also?
Matthias

**Comment by prbt2016** [comment]
Hello ,

I didn't use that single file installer install.php. I used https://www.sofawiki.com/site/files/snapshot.zip and performed the manual installation.  Could you please check the install with the same?.

**Comment by bellenuit** [comment]
I cannot reproduce it with this procedure, either.

**Comment by prbt2016** [comment]
Hello,

Is it possible that you could try and reproduce it on another environment or any other turnaround that can fix the above issue?.

Regards.

**Comment by prbt2016** [comment]
Hello ,

All the above issues are solved in 3.7.9 except this one : 

After I click on New -> Upload -> Browse and select a image and write a name in the filename textbox and click 'Upload' the image upload breaks i.e the image name is printed twice without extension, as shown below: 

![test](https://user-images.githubusercontent.com/17871448/162708698-425e80e3-107b-48f5-88f4-4db30c5bf6a3.png)

![image](https://user-images.githubusercontent.com/17871448/162709965-aafac110-c9f0-4841-b405-09e00521b1a9.png)


Could you please fix this?
