### ISSUE TITLE
[Vuln]There is a reflected XSS vulnerability.

### ISSUE THREAD

**Issue by xul18** [bellenuit/sofawiki#26]
1. The variable name is being sanitized for XSS using the function swSimpleSanitize().
```
// index.php
$name = swGetArrayValue($_REQUEST,'name',$swMainName); 
$name = swSimpleSanitize($name); // XSS
```
2.  The function swSimpleSanitize() only filters "<" and ">".
```
// /inc/utilities.php
function swSimpleSanitize($s)
{
	// filters out XSS input to be used on variables that should not habe html code or exec code
	$s = str_replace("<","",$s);
	$s = str_replace(">","",$s);
	return $s;
}
```
3. Use payload to trigger reflected XSS.
**http://*.*.*.*/index.php?name=test%22%20onmouseover=alert(/xss/);%22**
![image](https://user-images.githubusercontent.com/22881765/225209969-a69b0a1b-3490-41dd-8429-013532d310ad.png)
![image](https://user-images.githubusercontent.com/22881765/225210005-5bb0cb43-b9b2-4155-b5f9-4040af280375.png)

**Comment by bellenuit** [comment]
hotfix 8e1a572b0f76c2649ad75362a662b5883f6fb215
