### ISSUE TITLE
Feature: user simulation mode

### ISSUE THREAD

**Issue by ursbraem** [bellenuit/sofawiki#4]
It would be cool to have a simulation mode for admins (might also be useful for support, not only development) where you can switch to exactly the rights of another user (group) without having the credentials (as seen in TYPO3 https://docs.typo3.org/typo3cms/GettingStartedTutorial/UserManagement/BackendUsers/Index.html#simple-editor )

**Comment by bellenuit** [comment]
Added as alt User in 1.8.0.

**Comment by ursbraem** [comment]
wohooo!
