### ISSUE TITLE
Query ORDER case insensitive

### ISSUE THREAD

**Issue by FPSYX** [bellenuit/sofawiki#7]
Query ORDER is currently case sensitive, which produces weird results in alphabetical lists. Is there a reason for that, or could it be changed to be case insensitive?

**Comment by bellenuit** [comment]
ORDER is case insensitive on some system and sensitive on others (sqlite). 
But I agree there could be a modifier NOCASE as are currently NUMERIC, URL and FAMILYNAME.
I will implement that.

**Comment by bellenuit** [comment]
1.8.2

**Comment by FPSYX** [comment]
It should probably the other way around : insensitive unless specified (ORDER x ASC CASE). Most common use cases are case insensitive (no?), there's a reason all the major OSs behave this way by default. It doesn't really make sense to have to type an extra keyword for the 99% of the time.

Maybe WHERE should also be case insensitive unless specified (WHERE x =* y CASE) ? It's a bit silly having to do things like that : 
| SELECT label FROM producer WHERE label =* a
| SELECT label FROM producer WHERE label =* A
| UNION
